### ISSUE TITLE
Issue when training on Mouse Genome

### ISSUE THREAD

**Issue by jmyslins** [GET-Foundation/get_model#33]
Thank you for sharing your work! 

I have been attempting to run the steps outlined in finetune_pbmc.ipynb on a mouse dataset. I have already run the steps in prepare_pbmc.ipynb using all chromosomes. However I am getting an error when I run the following code:

```
celltype_for_modeling = [
    'cnt',
    'dct1',
    'dct2',
    'endo',
    'ic-a',
    'ic-b',
    'int',
    'junk',
    'ki67+',
    'loh_td',
    'pc',
    'pt_s1',
    'pt_s2',
    'pt_s3',
    'tal',
    't_cell',
    'ureteral',
    'inj_dct',
    'inj_pt_s1_s2',
    'inj_pt_s3',
    'injured_tal',
    'macrophage',
    'myeloid',
    'neutrophil',
    'parietal_epi',
    'principal_like',
]

cfg = load_config(config_name="finetune_combined")
cfg.stage = "fit"
cfg.run.project_name = 'finetune_MRSA_combined'
cfg.run.run_name = 'training_from_finetune_MRSA_combined'
cfg.dataset.quantitative_atac = False
cfg.dataset.zarr_path = "./MRSA_multiome.zarr" 
cfg.dataset.celltypes = ','.join(celltype_for_modeling) 
cfg.finetune.checkpoint = "./checkpoint-best.pth" 
cfg.machine.num_devices=1 
cfg.machine.batch_size=8 
cfg.machine.output_dir = "./output/"
print(f"output path: {cfg.machine.output_dir}/{cfg.run.project_name}/{cfg.run.run_name}")
print(f"training for {cfg.training.epochs} epochs")
export_config(cfg, "exported_training_config.yaml")
cfg = load_config_from_yaml("exported_training_config.yaml")
trainer = run(cfg)
```

with the error terminating on run(cfg) with:

```---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[130], line 6
      4 from get_model.run_region import run_zarr as run
      5 print("zarr_path =", cfg.dataset.zarr_path)
----> 6 trainer = run(cfg) # run the finetuning, takes around 2 hours on one RTX 3090

File /N/get_model/run_region.py:438, in run_zarr(cfg)
    435 dm = RegionZarrDataModule(cfg)
    436 model.dm = dm
--> 438 return run_shared(cfg, model, dm)

File /N/get_model/run.py:740, in run_shared(cfg, model, dm)
    737 trainer = setup_trainer(cfg)
    739 if cfg.stage == "fit":
--> 740     trainer.fit(model, dm, ckpt_path=cfg.finetune.resume_ckpt)
    741 if cfg.stage == "validate":
    742     trainer.validate(model, datamodule=dm, ckpt_path=cfg.finetune.resume_ckpt)

File /N/GETmodel/getmodel/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:561, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    559 self.training = True
    560 self.should_stop = False
--> 561 call._call_and_handle_interrupt(
    562     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    563 )

File /N/GETmodel/getmodel/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py:48, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     46     if trainer.strategy.launcher is not None:
     47         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
---> 48     return trainer_fn(*args, **kwargs)
     50 except _TunerExitException:
     51     _call_teardown_hook(trainer)

File /N/GETmodel/getmodel/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:599, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    592     download_model_from_registry(ckpt_path, self)
    593 ckpt_path = self._checkpoint_connector._select_ckpt_path(
    594     self.state.fn,
    595     ckpt_path,
    596     model_provided=True,
    597     model_connected=self.lightning_module is not None,
    598 )
--> 599 self._run(model, ckpt_path=ckpt_path)
    601 assert self.state.stopped
    602 self.training = False

File /N/GETmodel/getmodel/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:988, in Trainer._run(self, model, ckpt_path)
    985 self._logger_connector.reset_metrics()
    987 # strategy will configure model and move it to the device
--> 988 self.strategy.setup(self)
    990 # hook
    991 if self.state.fn == TrainerFn.FITTING:

File /N/GETmodel/getmodel/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py:159, in Strategy.setup(self, trainer)
    156 self.model = self._setup_model(self.model)
    158 if trainer.state.fn == TrainerFn.FITTING:
--> 159     self.setup_optimizers(trainer)
    160 self.setup_precision_plugin()
    161 if trainer.state.fn == TrainerFn.FITTING:

File /N/GETmodel/getmodel/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py:139, in Strategy.setup_optimizers(self, trainer)
    132 """Creates optimizers and schedulers.
    133 
    134 Args:
    135     trainer: the Trainer, these optimizers should be connected to
    136 
    137 """
    138 assert self.lightning_module is not None
--> 139 self.optimizers, self.lr_scheduler_configs = _init_optimizers_and_lr_schedulers(self.lightning_module)

File /N/GETmodel/getmodel/lib/python3.10/site-packages/lightning/pytorch/core/optimizer.py:180, in _init_optimizers_and_lr_schedulers(model)
    177 """Calls `LightningModule.configure_optimizers` and parses and validates the output."""
    178 from lightning.pytorch.trainer import call
--> 180 optim_conf = call._call_lightning_module_hook(model.trainer, "configure_optimizers", pl_module=model)
    182 if optim_conf is None:
    183     rank_zero_warn(
    184         "`LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer",
    185     )

File /N/GETmodel/getmodel/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py:176, in _call_lightning_module_hook(trainer, hook_name, pl_module, *args, **kwargs)
    173 pl_module._current_fx_name = hook_name
    175 with trainer.profiler.profile(f"[LightningModule]{pl_module.__class__.__name__}.{hook_name}"):
--> 176     output = fn(*args, **kwargs)
    178 # restore current_fx when nested context
    179 pl_module._current_fx_name = prev_fx_name

File /N/get_model/run.py:525, in LitModel.configure_optimizers(self)
    522     return self.schedule[step_index-1] / self.cfg.optimizer.lr
    524 # Create the LambdaLR
--> 525 lr_scheduler = torch.optim.lr_scheduler.LambdaLR(
    526     optimizer,
    527     lr_lambda=lr_lambda,
    528 )
    530 # Let Lightning know: this scheduler is stepped each batch
    531 scheduler_config = {
    532     "scheduler": lr_scheduler,
    533     "interval": "step",  # call scheduler.step() every batch
    534     "frequency": 1,
    535 }

File /N/GETmodel/getmodel/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:338, in LambdaLR.__init__(self, optimizer, lr_lambda, last_epoch, verbose)
    334         raise ValueError(
    335             f"Expected {len(optimizer.param_groups)} lr_lambdas, but got {len(lr_lambda)}"
    336         )
    337     self.lr_lambdas = list(lr_lambda)
--> 338 super().__init__(optimizer, last_epoch, verbose)

File /N/GETmodel/getmodel/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:149, in LRScheduler.__init__(self, optimizer, last_epoch, verbose)
    147 patch_track_step_called(self.optimizer)
    148 self.verbose = _check_verbose_deprecated_warning(verbose)
--> 149 self._initial_step()

File /N/GETmodel/getmodel/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:154, in LRScheduler._initial_step(self)
    152 """Initialize step counts and perform a step."""
    153 self._step_count = 0
--> 154 self.step()

File /N/GETmodel/getmodel/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:241, in LRScheduler.step(self, epoch)
    239 if epoch is None:
    240     self.last_epoch += 1
--> 241     values = self.get_lr()
    242 else:
    243     warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)

File /N/GETmodel/getmodel/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:386, in LambdaLR.get_lr(self)
    383 """Compute learning rate."""
    384 _warn_get_lr_called_within_step(self)
--> 386 return [
    387     base_lr * lmbda(self.last_epoch)
    388     for lmbda, base_lr in zip(self.lr_lambdas, self.base_lrs)
    389 ]

File /N/GETmodel/getmodel/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:387, in <listcomp>(.0)
    383 """Compute learning rate."""
    384 _warn_get_lr_called_within_step(self)
    386 return [
--> 387     base_lr * lmbda(self.last_epoch)
    388     for lmbda, base_lr in zip(self.lr_lambdas, self.base_lrs)
    389 ]

File /N/get_model/run.py:522, in LitModel.configure_optimizers.<locals>.lr_lambda(step_index)
    517 def lr_lambda(step_index):
    518     # step_index will go from 0 ... (max_steps - 1)
    519     # (Lightning calls scheduler.step() after each batch if interval="step")
    520     # if self.schedule[step_index] is the actual LR value, we divide by initial lr
    521     # because LambdaLR multiplies the optimizer’s base LR by this factor
--> 522     return self.schedule[step_index-1] / self.cfg.optimizer.lr

IndexError: index -1 is out of bounds for axis 0 with size 0
```

I am unsure what is causing this as I can't discern what is causing the issue in the run.py step. Is there something I have set incorrectly or any step I have missed that could be causing this? Thank you very much for your time.

**Comment by fuxialexander** [comment]
Are you using the newest docker image? This scheduler issue should have be fixed previously.

**Comment by jmyslins** [comment]
Thank you for your response, I copied the repo on the 14th so I was using the version from that time. 
I am currently using the run from
```from get_model.run_region import run_zarr as run```

Is that that the correct one to use? I saw that run.py was changed for mouse genome last week, but I am not sure which run function would be used if that is the issue since it does not appear to contain run_zarr.

**Comment by fuxialexander** [comment]
The function should be fine. Does this problem exist when using a different (say 10) `cfg.training.epoch`?

**Comment by jmyslins** [comment]
I tried changing the epoch to 10 instead of 100 and there did not seem to be any change in the error I received. 

I am now wondering if the way I built my dataset is the issue. I tried following the prepare_pbmc.ipynb script using my matrix files as well aswget https://resources.altius.org/~jvierstra/projects/motif-clustering/releases/v1.0/mm10.archetype_motifs.v1.0.bed.gz. But in the first step I downloaded mouse CREs https://downloads.wenglab.org/V3/mm10-cCREs.bed

Below will be the code I ran for prepare_pbmc.ipynb, but how should I have set things up immediately after this step? I was trying to figure out how to correctly build my config.yaml file and ended up copying one of them and heavily modifying it.

Here is the prepare_pbmc.ipynb script:
```
#%%
from pathlib import Path

import numpy as np
import snapatac2 as snap
from gcell._settings import get_setting

annotation_dir = get_setting('annotation_dir')
print("gcell currently using annotation directory:", annotation_dir)

import pandas as pd
import pyranges as pr

cre1 = pd.read_csv(
    '/analysis/foundation/mm10_cCRE_reformatted.tsv',
    sep='\t',
    comment='#'
)


cre1 = pr.PyRanges(cre1).sort()
cre1
```

```
 	Chromosome 	Start 	End 	Class 	Present in fetal tissues 	Present in adult tissues 	CRE module
0 	chr1 	3119617 	3119911 	Distal 	unknown 	unknown 	NaN
1 	chr1 	3119914 	3120119 	Distal 	unknown 	unknown 	NaN
2 	chr1 	3120346 	3120662 	Distal 	unknown 	unknown 	NaN
3 	chr1 	3292622 	3292971 	Distal 	unknown 	unknown 	NaN
4 	chr1 	3322453 	3322797 	Promoter Proximal 	unknown 	unknown 	NaN
```

```
import pandas as pd
from pyranges import PyRanges as pr
import scanpy as sc

ad = sc.read_10x_h5('outs/filtered_feature_bc_matrix.h5', gex_only=False)
ad.var_names_make_unique()
ad

#AnnData object with n_obs × n_vars = 34594 × 179804
#    var: 'gene_ids', 'feature_types', 'genome', 'interval'

peaks = ad.var.query('feature_types == "Peaks"').interval.str.split(':|-').tolist()
peaks = pd.DataFrame(peaks, columns=['Chromosome', 'Start', 'End'])
peaks['Start'] = peaks['Start'].astype(int)
peaks['End'] = peaks['End'].astype(int)
peaks = pr(peaks, int64=True).sort()
peaks.df.shape

#(147519, 3)

# peak / cre + cre 
# find all peaks that don't overlap with cre; -> non_overlap_peaks
non_overlap_peaks = peaks.overlap(cre1, invert=True)
# concat with cre and sort
total_peaks = pd.concat([non_overlap_peaks.df, cre1.df], ignore_index=True)
total_peaks = pr(total_peaks, int64=True).sort()
# remove chromosome M, Y and those not start with chr
total_peaks = total_peaks.df.query('Chromosome.str.startswith("chr") & ~Chromosome.str.endswith("M") & ~Chromosome.str.endswith("Y") & ~Chromosome.str.startswith("chrUn")')
total_peaks.shape

#(398060, 7)

import matplotlib.pyplot as plt
import seaborn as sns

# Create the figure and axes
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

# Plot the PBMC Peaks Length Distribution
sns.histplot(peaks.End - peaks.Start, ax=ax1)
ax1.set_title('PBMC Peaks Length Distribution')

# Plot the Training CRE Length Distribution
sns.histplot(cre.End - cre.Start, ax=ax2)
ax2.set_title('Training CRE Length Distribution')

##scored annotated seurat object 
rna_filtered = sc.read('analysis/seurat_anndata_fullyscored.h5ad')
ad = ad[ad.obs.index.isin(rna_filtered.obs.index.values)]
ad

#View of AnnData object with n_obs × n_vars = 26579 × 179804
#    var: 'gene_ids', 'feature_types', 'genome', 'interval'

barcode_to_celltype = rna_filtered.obs.to_dict()['newIdents']
ad.obs['cell_type'] = ad.obs.index.map(barcode_to_celltype)
ad.obs.head()

# 	cell_type
#AAACAGCCACCGGCTA-1 	DCT1
#AAACAGCCACCTAATG-4 	PT_S3
#AAACAGCCACCTATAG-2 	inj_PT_S1_S2
#AAACAGCCACCTGGTG-4 	Int
#AAACAGCCACGTAAGG-1 	PC

import numpy as np
ad_rna = ad[:, np.where(ad.var.feature_types == 'Gene Expression')[0]]
ad_rna

ad_atac = ad[:, np.where(ad.var.feature_types == 'Peaks')[0]]
ad_atac

# %%

cell_number = ad_atac.obs.groupby('cell_type', observed=False).size().to_dict()
print("The following cell types have more than 100 cells and library size > 3M, adding them to celltype_for_modeling")
celltype_for_modeling = []
for cell_type in cell_number:
    if cell_number[cell_type] > 100:
        celltype_for_modeling.append(cell_type)
        libsize = int(ad_atac[ad_atac.obs.cell_type == cell_type].X.sum())
        if libsize > 3000000:
            print(f"{cell_type} number of cells: {cell_number[cell_type]}, library size: {libsize}")

```

```
The following cell types have more than 100 cells and library size > 3M, adding them to celltype_for_modeling
CNT number of cells: 413, library size: 4182680
DCT1 number of cells: 815, library size: 8154591
DCT2 number of cells: 794, library size: 9032647
Endo number of cells: 1170, library size: 11288274
IC-A number of cells: 446, library size: 5062711
IC-B number of cells: 436, library size: 5524513
Int number of cells: 669, library size: 8637098
Junk number of cells: 562, library size: 10353266
Ki67+ number of cells: 120, library size: 3024553
LOH_TD number of cells: 313, library size: 4154061
PC number of cells: 645, library size: 8193174
PT_S1 number of cells: 2480, library size: 31432936
PT_S2 number of cells: 3648, library size: 51217040
PT_S3 number of cells: 1965, library size: 34970472
TAL number of cells: 3001, library size: 29066506
inj DCT number of cells: 809, library size: 9544687
inj_PT_S1_S2 number of cells: 3578, library size: 54939472
inj_PT_S3 number of cells: 744, library size: 14662633
injured TAL number of cells: 1228, library size: 13504006
myeloid number of cells: 305, library size: 3054184
neutrophil number of cells: 1310, library size: 7998251
```

```
celltype_for_modeling = ['CNT',
 'DCT1',
 'DCT2',
 'Endo',
 'IC-A',
 'IC-B',
 'Int',
 'Junk',
 'Ki67+',
 'LOH_TD',
 'PC',
 'PT_S1',
 'PT_S2',
 'PT_S3',
 'TAL',
 'T_cell',
 'Ureteral',
 'inj DCT',
 'inj_PT_S1_S2',
 'inj_PT_S3',
 'injured TAL',
 'macrophage',
 'myeloid',
 'neutrophil',
 'parietal_epi',
 'principal_like']

import pandas as pd
from pyranges import PyRanges as pr
def get_peak_from_snapatac(atac: snap.AnnData):
    """
    Get the peak names from the snapatac object.

    Args:
        atac: snapatac2 processed AnnData object

    Returns:
        peak_names: pandas DatasFrame with the peak names
    """
    peak_names = pd.DataFrame(atac.var.index.str.split('[:-]').tolist(), columns=['Chromosome', 'Start', 'End'])
    peak_names['Start'] = peak_names['Start'].astype(int)
    peak_names['End'] = peak_names['End'].astype(int)
    return peak_names

peaks = get_peak_from_snapatac(ad_atac)
peaks.shape

#(147519, 3)

# %%
def get_peak_acpm_for_cell_type(atac: snap.AnnData, cell_type: str):
    """
    Get the peak acpm for a given cell type.
    """
    peaks = get_peak_from_snapatac(atac)
    counts = np.array(atac[atac.obs.cell_type == cell_type].X.sum(0)).flatten()
    acpm = np.log10(counts / counts.sum() * 1e5 + 1)
    peaks['aCPM'] = acpm/acpm.max()
    peaks = peaks.query('Chromosome.str.startswith("chr") & ~Chromosome.str.endswith("M") & ~Chromosome.str.endswith("Y") & ~Chromosome.str.startswith("chrUn")')
    peaks = pr(peaks, int64=True).sort().df
    return peaks

# %%
for cell_type in celltype_for_modeling:
    peaks = get_peak_acpm_for_cell_type(ad_atac, cell_type)
    peaks.to_csv(f'{cell_type.replace(" ", "_").lower()}.atac.bed', sep='\t', index=False, header=False)

peaks['length'] = peaks['End'] - peaks['Start']

peaks

#0 	chr1 	3372413 	3373303 	0.046110 	890
#1 	chr1 	3395223 	3396062 	0.000000 	839
#2 	chr1 	3399697 	3400606 	0.012727 	909
#3 	chr1 	3401102 	3401810 	0.000000 	708
#4 	chr1 	3405589 	3406441 	0.024583 	852

# %%
def get_rna_for_cell_type(rna: snap.AnnData, cell_type: str):
    """
    Get the rna for a given cell type.
    """
    counts = rna[rna.obs.cell_type == cell_type].X.sum(0)
    counts = np.log10(counts / counts.sum() * 1e6 + 1)
    counts = np.array(counts).flatten()
    rna_tpm = pd.DataFrame(counts, columns=['TPM'])
    rna_tpm['gene_name'] = rna.var.index
    return rna_tpm[['gene_name', 'TPM']].sort_values(by='gene_name', ascending=True)

#%%
for cell_type in celltype_for_modeling:
    rna_tpm = get_rna_for_cell_type(ad_rna, cell_type)
    rna_tpm.to_csv(f'{cell_type.replace(" ", "_").lower()}.rna.csv', index=False)

import os
from pathlib import Path

from gcell._settings import get_setting
from preprocess_utils import (
    add_atpm,
    add_exp,
    create_peak_motif,
    download_motif,
    get_motif,
    query_motif,
)

annotation_dir = Path(get_setting('annotation_dir'))
print("gcell currently using annotation directory:", annotation_dir)

#gcell currently using annotation directory: /.gcell_data/annotations

motif_bed = str(annotation_dir / "mm10.archetype_motifs.v1.0.bed.gz")

peak_bed = "neutrophil.atac.bed" # since all cell types share the same peak set, when querying motifs, we can just use one cell type to query motifs.
peaks_motif = query_motif(peak_bed, motif_bed)
get_motif_output = get_motif(peak_bed, peaks_motif)

#Peak motif extraction completed. Results saved in get_motif.bed

create_peak_motif(get_motif_output, "MRSA_multiome.zarr", peak_bed) # all cell types will later be added to the same zarr file as we use the same peak set.

from pathlib import Path

# Get current directory
current_dir = Path('.')

# Find all files ending in .atac.bed
atac_files = current_dir.glob("*.atac.bed")

# Extract everything before '.atac.bed'
celltype_for_modeling = [f.name.replace('.atac.bed', '') for f in atac_files]

print(celltype_for_modeling)

#['inj_pt_s1_s2', 'myeloid', 'ureteral', 'int', 'injured_tal', 'parietal_epi', 'dct2', 'loh_td', 'pt_s2', 't_cell', 'principal_like', 'inj_dct', 'ic-a', 'tal', 'junk', 'neutrophil', 'macrophage', 'inj_pt_s3', 'dct1', 'cnt', 'endo', 'pc', 'pt_s1', 'ki67+', 'pt_s3', 'ic-b']

for cell_type in celltype_for_modeling:
    add_atpm(
        "MRSA_multiome.zarr",
        f"{cell_type.lower()}.atac.bed",
        cell_type,
    )
```

```
0            chr1    3372413    3373303  0.008811      chr1:3372413-3373303
1            chr1    3395223    3396062  0.000000      chr1:3395223-3396062
2            chr1    3399697    3400606  0.017230      chr1:3399697-3400606
3            chr1    3401102    3401810  0.000000      chr1:3401102-3401810
4            chr1    3405589    3406441  0.013067      chr1:3405589-3406441
...           ...        ...        ...       ...                       ...
147454       chrX  170004924  170005836  0.051056  chrX:170004924-170005836
147455       chrX  170673022  170673868  0.057815  chrX:170673022-170673868
147456       chrX  170674408  170675336  0.047583  chrX:170674408-170675336
147457       chrX  170757848  170758754  0.017230  chrX:170757848-170758754
147458       chrX  170880712  170881614  0.079729  chrX:170880712-170881614
```

```
for cell_type in celltype_for_modeling:
    add_exp(
        "MRSA_multiome.zarr",
        f"{cell_type.lower()}.rna.csv",
        f"{cell_type.lower()}.atac.bed",
        cell_type,
        assembly="mm10",
        version="M30",
        extend_bp=300, # extend TSS region to 300bp upstream and downstream when overlapping with peaks
    id_or_name="gene_name", # use gene_name or gene_id to match the gene expression data, checkout your rna.csv file column names, should be either [gene_name, TPM] or [gene_id, TPM]
)
```


Here is my modified exported_training_config.yaml file that I ended up saving the cfg settings:

```
training:
  save_ckpt_freq: 1
  epochs: 10
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false
dataset:
  zarr_path: ./MRSA_multiome.zarr
  quantitative_atac: false
  sampling_step: 100
  mask_ratio: 0.0
  celltypes: cnt,dct1,dct2,endo,ic-a,ic-b,int,junk,ki67+,loh_td,pc,pt_s1,pt_s2,pt_s3,tal,t_cell,ureteral,inj_dct,inj_pt_s1_s2,inj_pt_s3,injured_tal,macrophage,myeloid,neutrophil,parietal_epi,principal_like
optimizer:
  lr: 0.0001
  min_lr: 1.0e-06
  weight_decay: 0.05
  opt: adamw
  opt_eps: 1.0e-08
  opt_betas:
  - 0.9
  - 0.999
run:
  project_name: finetune_MRSA_combined
  run_name: training_from_finetune_MRSA_combined
  use_wandb: false
finetune:
  pretrain_checkpoint: false
  strict: true
  use_lora: false
  checkpoint: ./checkpoint-best.pth
  patterns_to_freeze: []
  model_key: model
  rename_config:
    blocks.: encoder.blocks.
    fc_norm.: encoder.norm.
    encoder.head.: head_mask.
    encoder.region_embed: region_embed
    region_embed.proj.: region_embed.embed.
    encoder.cls_token: cls_token
    head.: head_exp.head.
task:
  layer_names:
  - region_embed
  test_mode: interpret
  gene_list: []
model:
  _target_: get_model.model.model.GETRegionFinetuneHiCOE
  cfg:
    num_regions: 200
    num_motif: 284
    embed_dim: 768
    num_layers: 12
    num_heads: 12
    dropout: 0.1
    output_dim: 2
    flash_attn: false
    pool_method: mean
    distance_contact_map:
      freezed: true
    region_embed:
      num_regions: ${model.cfg.num_regions}
      num_features: ${model.cfg.num_motif}
      embed_dim: ${model.cfg.embed_dim}
    encoder:
      num_heads: ${model.cfg.num_heads}
      embed_dim: ${model.cfg.embed_dim}
      num_layers: ${model.cfg.num_layers}
      drop_path_rate: ${model.cfg.dropout}
      drop_rate: 0
      attn_drop_rate: 0
      use_mean_pooling: false
      flash_attn: ${model.cfg.flash_attn}
    header_hic:
      input_dim: 128
      hidden_dim: 64
      output_dim: 1
    mask_token:
      embed_dim: ${model.cfg.embed_dim}
      std: 0.02
    loss:
      components:
        hic:
          _target_: torch.nn.MSELoss
          reduction: mean
      weights:
        hic: 1.0
    metrics:
      components:
        hic:
        - pearson
        - spearman
        - r2
machine:
  data_path: /analysis/foundation/get_data/
  codebase: /analysis/foundation/get_model/
  output_dir: /analysis/foundation/
  num_devices: 0
  num_workers: 2
  batch_size: 8

```

Does this appear correct or is there some sort of basic script I should be using to build off of with different settings? 

Thank you very much for your help with this so far.
